### ISSUE TITLE
Build process fail

### ISSUE THREAD

**Issue by Softsapiens** [paf31/lambdaconf-2015#2]
Hello,
I'm trying to build the server with docker using this Dockerfile:

```
FROM node:latest

ENV PURESCRIPT_DOWNLOAD_SHA1 0eef2324808b4ad1688d344800e14270206276b9

RUN cd /opt \
    && wget https://github.com/purescript/purescript/releases/download/v0.6.9.5/linux64.tar.gz \
    && echo "$PURESCRIPT_DOWNLOAD_SHA1 linux64.tar.gz" | sha1sum -c - \
    && tar -xvf linux64.tar.gz \
    && rm /opt/linux64.tar.gz

ENV PATH /opt/purescript:$PATH

RUN npm install -g pulp@">=3.0.0 <4.0.0" bower

RUN echo '{ "allow_root": true }' > /root/.bowerrc

RUN mkdir -p /code/purescript && cd /code/purescript \
    && git clone https://github.com/paf31/lambdaconf-2015.git

RUN cd /code/purescript/lambdaconf-2015/server \
    && bower update
RUN npm install

CMD ["/opt/purescript/psci"]
```

All is correct until the `pulp run`command. The build fails with that message:
`* Building project in /code/purescript/lambdaconf-2015/server
Module Prelude has been defined multiple times
See https://github.com/purescript/purescript/wiki/Error-Code-RedefinedModule for more information, or to contribute content related to this error.
`

Do you see the problem?

Thanks in advance,
Dani

**Comment by paf31** [comment]
It sounds like Bower is installing a more recent dependency somewhere, and you're getting `purescript-prelude`. Does `bower_components/purescript-prelude` exist in the container? It shouldn't.

**Comment by Softsapiens** [comment]
You are right!
That was the problem. Now build is ok, but `pulp run`returns another error:

```
/code/purescript/lambdaconf-2015/server/output/Data.Foreign.EasyFFI/index.js:10
    unsafeForeignProcedure: unsafeForeignProcedure,
                            ^

ReferenceError: unsafeForeignProcedure is not defined
    at Object.<anonymous> (/code/purescript/lambdaconf-2015/server/output/Data.Foreign.EasyFFI/index.js:10:29)
    at Module._compile (module.js:397:26)
```

Don't worry, don't mind... I have ported the code to psc 0.7.6 and migrate to more recent versions of used libraries. And it's working...

Let me ask you a question not related to this. Which env are you using to develop purescript? I actually use last versions of atom + plugin + psc-ide-server, and it doesn't work very well... 

For your interest, I'm from Barcelona, and I'm trying to find a project/job position related to purescript (or haskell, or any pure language), but for now it not seems easy... I'm going to try hard!  :-)

Thanks for your time, and your amazing work with Purescript + Libs. I'm fan of it
